sprint-5
ClevertecFrontendLab/agtugchik pull request #5
Opened 2024-03-26 18:25 UTC by agtugchik

2024-03-26 18:27 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711477660/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711477660/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711477660/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711477660/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711477660/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711477660/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711477660/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711477660/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711477660/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711477660/settings-sider-pro_833x900.png)

2024-03-26 19:26 UTC, byshlata commented
на этом скрине должна быть фотка, там какой-то хлопчик должен быть. Пока в тесте его не будет, значит он работает неправильно. 
![image](https://github.com/ClevertecFrontendLab/agtugchik/assets/70332441/d1fe594e-bd7e-444d-8d5a-4d6173520689)

2024-03-26 19:31 UTC, byshlata requested changes
замечание по коду. Перенести все переменные в css во всем проекте

2024-03-26 19:31 UTC, byshlata commented on src/components/drawer-tarif-cost/drawer-tarif-cast.module.scss
> +      margin-right: 48px;
в переменные

2024-03-26 19:31 UTC, byshlata commented on src/components/drawer-tarif-cost/drawer-tarif-cast.module.scss
> +        font-size: 14px;
в переменные

2024-03-26 19:31 UTC, byshlata commented on src/components/drawer-tarif-cost/drawer-tarif-cast.module.scss
> +        font-size: 16px;
в переменные

2024-03-26 19:31 UTC, byshlata commented on src/components/drawer-tarif-cost/drawer-tarif-cost.tsx
> +import cl from './drawer-tarif-cast.module.scss';
styles

2024-03-26 19:31 UTC, byshlata commented on src/components/tariff-comparison/tariff-comparison.module.scss
> +    row-gap: 16px;
в переменные

2024-03-26 19:31 UTC, byshlata commented on src/components/tariff-comparison/tariff-comparison.module.scss
> +      background-color: #f0f5ff;
в переменные, цвета? padding? margin? gap? font-size

2024-03-26 19:31 UTC, byshlata commented on src/components/u-i/custom-header/custom-header.tsx
> +    breadcrumbItems?: Array<string | ReactNode>;
необязательные после обязательных

2024-03-26 20:14 UTC, agtugchik commented
> на этом скрине должна быть фотка, там какой-то хлопчик должен быть. Пока в тесте его не будет, значит он работает неправильно. ![image](https://private-user-images.githubusercontent.com/70332441/317011757-d1fe594e-bd7e-444d-8d5a-4d6173520689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODIxNDIsIm5iZiI6MTcxMTQ4MTg0MiwicGF0aCI6Ii83MDMzMjQ0MS8zMTcwMTE3NTctZDFmZTU5NGUtYmQ3ZS00NDRkLThkNWEtNGQ2MTczNTIwNjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE5MzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MzFmYmMyOGQzMWE4MzQ0ODM5NTY1MmVmZmI1MDk4NjU5MDU2MTA5NDA4ZjQxZDRlOGJmNjFiOTlkYTQ4MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.swsXg8FFbOm_X8hGKivbFl2ZUWgsIsiuneDTwDUmGeQ)

Принял. Это я исправил. Хочу сразу спросить что вы хотите что бы я вынес в константы и куда, что бы несколько раз не переделывать. И я правильyj понял, что мjдули стилей нужно переименовать в styles из cl?

2024-03-27 05:35 UTC, VitalyHanchar commented on .eslintrc.cjs
>  module.exports = {
Тут поехало, переносы, картинки.
![image](https://github.com/ClevertecFrontendLab/agtugchik/assets/122732222/fe34b15c-c9ba-4499-be54-a1c7eff06a52)

2024-03-27 05:38 UTC, VitalyHanchar commented on .eslintrc.cjs
>      root: true,
Тут нужно указать размер файла. "до 5 МБ"
![image](https://github.com/ClevertecFrontendLab/agtugchik/assets/122732222/698ceca8-cc19-48f1-a5cf-c122bb7ca2b7)

2024-03-27 05:44 UTC, VitalyHanchar commented on .eslintrc.cjs
>      env: { browser: true, es2020: true },
А где фото?
![image](https://github.com/ClevertecFrontendLab/agtugchik/assets/122732222/a23bae5c-d9cb-4547-b259-eee80bb6314f)

2024-03-27 05:48 UTC, VitalyHanchar commented on .eslintrc.cjs
> -    extends: [
?
![image](https://github.com/ClevertecFrontendLab/agtugchik/assets/122732222/d37a0749-a5ca-4f66-a891-4cc204408847)

2024-03-27 05:50 UTC, VitalyHanchar commented on .eslintrc.cjs
> -        'eslint:recommended',
А почему тут меню раскрыто?
![image](https://github.com/ClevertecFrontendLab/agtugchik/assets/122732222/0a670cd4-2c8f-4d5d-b9a4-8d86c61333ce)

2024-03-27 05:56 UTC, VitalyHanchar requested changes
-

2024-03-27 15:48 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711554510/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711554510/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711554510/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711554510/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711554510/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711554510/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711554510/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711554510/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711554510/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/agtugchik/1711554510/settings-sider-pro_833x900.png)

2024-03-27 18:25 UTC, byshlata approved these changes

2024-03-27 18:45 UTC, VitalyHanchar approved these changes

2024-03-27 18:50 UTC, merged